"""added contact_number to leave

Revision ID: 310176b53be7
Revises: f35967469a47
Create Date: 2026-04-24 22:11:47.486106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '310176b53be7'
down_revision = 'f35967469a47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leaves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_number', sa.String(length=15), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leaves', schema=None) as batch_op:
        batch_op.drop_column('contact_number')

    # ### end Alembic commands ###
