"""empty message

Revision ID: 714f3f2496a6
Revises: 89e51808596d
Create Date: 2026-04-23 12:59:45.738953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '714f3f2496a6'
down_revision = '89e51808596d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
