"""updated table

Revision ID: ba19a38c2252
Revises: 310176b53be7
Create Date: 2026-04-24 22:39:25.990489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba19a38c2252'
down_revision = '310176b53be7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leaves', schema=None) as batch_op:
        batch_op.drop_column('pass_generated')
        batch_op.drop_column('pass_qr_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leaves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pass_qr_code', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pass_generated', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
